%% Setup The Injection Well
rxy = sqrt((Lx/nx)^2 + (Ly/ny)^2);
xy = G.cells.centroids(:,1:2);
InjWCells = find( sum(bsxfun(@minus,xy,[1437.5 487.5]).^2,2)<rxy);

Injector = addWell( [],  G, rock, ...
                    InjWCells,  ...
                    'InnerProduct', 'ip_tpf',...
                    'Type', 'rate', 'Val', rate, ...
                    'Comp_i', [1 0], 'Name', 'I', 'Dir','z');

%% Setup The Horizontal Producer
rxz = sqrt((Lx/nx)^2 + (Lz/nz)^2);
xz = G.cells.centroids(:, [1, 3]);
y = G.cells.centroids(:, 2);
HorizPoriducerCells = find((sum(bsxfun(@minus,xz,[67.5 2070]).^2,2)<rxz) & (y>50)&(y<950));
HorizontalProducer = addWell(Injector, G, rock, HorizPoriducerCells, ...
                            'InnerProduct', 'ip_tpf', ...
                            'Type', 'bhp', 'Val', 100*barsa, ...
                            'Comp_i', [0 1], 'Name', 'P', 'Dir','y');

